DROP TABLE IF EXISTS events;

CREATE TABLE events (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    owner_id integer REFERENCES users(id) NOT NULL,
    event_name TEXT NOT NULL,
    date TIMESTAMP,
    description text,
    location text not null,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    date_modified TIMESTAMP
    
);

ALTER TABLE events ALTER COLUMN id RESTART WITH 1000000;